id: I935CA8C2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-02-20T14:41:43+00:00'
last_modified: '2022-06-09T17:42:20.449077+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23923
  title: དཔལ་ཇོ་ནང་བའི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0D3A:
      image_group_id: I3528
      title: ''
      total_pages: 1476
      order: 1
      base_file: 0D3A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
