id: opecha:P000281
initial_creation_type: ocr
source_metadata:
  id: bdr:W23923
  title: དཔལ་ཇོ་ནང་བའི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས
  volume:
    289b92bc707943a5ad545743a03ce818:
      image_group_id: I3528
      title: ''
      volume_number: 1
      total_pages: 1476
  author: ''
ebook_metadata:
  title: དཔལ་ཇོ་ནང་བའི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས
  author: ''
  sku: P000281
  cover: cover.jpg
  layers:
  - pagination
