id: P000281
initial_creation_type: ocr
created_at: 20/02/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W23923
  title: དཔལ་ཇོ་ནང་བའི་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས
  author: ''
  volumes:
    289b92bc707943a5ad545743a03ce818:
      image_group_id: I3528
      title: ''
      volume_number: 1
      total_pages: 1476
      base_file: v001.txt
